### ISSUE TITLE
无法下载PDF文档

### ISSUE THREAD

**Issue by goubulidetutuding** [babbittry/Csharp-notes#1]

**Comment by babbittry** [comment]
可能是因为 Github 访问太慢了，导致访问失败，我已经上传百度云，链接: https://pan.baidu.com/s/1Yi15pmF5m-FY2WWHvDoz0g 提取码: 4z5b 。

**Comment by babbittry** [comment]
也可以在线观看，链接：https://babbittry.github.io/Csharp-notes/
